### PR TITLE
Feature: Add Gallery Page #289

### PR DESCRIPTION
**Pull request by paulathevalley**
This PR adds the `/gallery` page and a bunch of examples. 

TODO (in a separate PR): Add an individual gallery page for each example.

screenshot: 
screencapture-localhost-3000-gallery-1494270014381

### CODE REVIEW

**Comment by boygirl** [comment]
@paulathevalley this is looking great! I love how easy it's going to be to add examples. I think the examples should be larger, since so many of them are interactive. Maybe more like 4 / row (I see 6 / row on my 13" screen). There should also be some indication that each gallery item is clickable. Maybe the border box can change color?

**Comment by paulathevalley** [comment]
@boygirl :+1: I can definitely make them larger. Since none of the individual gallery pages are present, I refrained from making them look clickable right now, but when I PR the individual pages I will definitely make sure they look clickable!

**Comment by paulathevalley** [comment]
Update to 4 per row: 

screen shot 2017-05-08 at 2 00 50 pm

**Comment by boygirl** [comment]
@paulathevalley approved!

**Pull request merged**
