### PR TITLE
Update gatsby branch

### PR DESCRIPTION
**Pull request by boygirl**
@paulathevalley 

This PR reconciles your gatsby branch with current master and adds sidebar search functionality

I think I've mangled some of the sidebar styles, and I think there's probably still some infrastructure stuff that needs to be cleaned up.

### CODE REVIEW

**Comment by boygirl** [comment]
closes https://github.com/FormidableLabs/victory-docs/issues/448
closes https://github.com/FormidableLabs/victory-docs/issues/443
closes https://github.com/FormidableLabs/victory-docs/issues/442
closes https://github.com/FormidableLabs/victory-docs/issues/449
closes https://github.com/FormidableLabs/victory-docs/issues/447

**Comment by boygirl** [comment]
@paulathevalley everything here is working properly in development, but when I try to serve the built version none of the links work. Refreshing to something like /docs just renders the index. Zero errors in the console. I'm at a loss. Any ideas?

**Comment by boygirl** [comment]
Sounds like this issue: https://github.com/gatsbyjs/gatsby/issues/3104

**Comment by paulathevalley** [comment]
@boygirl I am seeing the same behavior with `yarn run build`, but in `yarn run build:pp` the links appear to be working correctly. I was hoping path prefix would make it easier to test and deploy the build!

**Comment by boygirl** [comment]
Progress: cloning the repo fresh results in actual console errors: 

```
Uncaught Error: Cannot find module "gatsby-module-loader?name=component---node-modules-gatsby-plugin-offline-app-shell-js!/Users/boygirl/formidable/victory-docs/node_modules/gatsby-plugin-offline/app-shell.js"
```

**Pull request merged**
