### PR TITLE
287 search sidebar

### PR DESCRIPTION
**Pull request by ianwsperber**
Addresses #287 to create a searchable sidebar.

sidebar-search

My implementation required a large number of refactors to make the sidebar content A. Searchable & B. Reducible. 

Given that the content of the sidebar is inherently a tree, and that traversing a tree is expensive/complicated (recursion!), I created a few different data structures to keep things speedy. Where possible I frontloaded processing in the application bootstrapping. There are improvements that can be made in the future for performance (and likely readability! I feel like I deep dived on this too much). Since we need to display the _parents_ of matched terms, in addition to the terms themselves, we currently have a naive implementation that runs loops within a loop, for example (O^2!). All in all it's relatively snappy on my local machine though.

As the above gif shows, when you have text in the search box headers are _no longer_ collapsable. I can change this behavior if desired, but we may wish to discuss the nuances of that.

I think it'd be great if we added fuzzy search in the future too ⛱ 

All credits to @paulathevalley for styling the input 😄

### CODE REVIEW

**Comment by boygirl** [comment]
@ianwsperber something this is going to need (that can be done in a separate ticket if you like) is to preemptively match on a list of common props https://github.com/FormidableLabs/victory-docs/issues/303

We'll end up with a `docs/common-props` ecology doc to match all of these to, but it should act slightly differently than other matching, in that the match will _only_ show up in the common props list rather than opening all other headings. _i.e._ matching to `style` will show up in Docs -> Common Props -> style, but not Docs -> VictoryPie -> Props -> style etc. 

Also, we should blacklist "Props"  and "Standard Container Props" as a matches.

**Comment by boygirl** [comment]
I'm also seeing some strange matches: 
screen shot 2017-05-09 at 10 35 57 am

**Comment by boygirl** [comment]
@ianwsperber this looks good to me. Good to merge once CI passes. Can you open a separate issue about retaining the search string when switching between /docs and /guides?

**Comment by ianwsperber** [comment]
Will do @boygirl!

**Comment by boygirl** [comment]
🚀 Approved!

**Pull request merged**
