### PR TITLE
Update formidable-landers to v8.4.0

### PR DESCRIPTION
**Pull request by ryan-roemer**
Opened automagically by multibot

### CODE REVIEW

**Comment by boygirl** [comment]
@ryan-roemer this looks good, but I have a fun new css-loader error popping up on master with a fresh yarn install. I'll get that cleaned up today and then merge this branch.

**Comment by ryan-roemer** [comment]
@boygirl -- Thanks. Point me to the `css-loader` error. Turns out we've had some "accidentally working" things going on for a while in our landers libs + support stuff, that us removing all extra / unused deps upstream is surfacing just now...

**Comment by boygirl** [comment]
@ryan-roemer with a fresh yarn install, `yarn start` will fail with the following:

```
 ERROR  Failed to compile with 3 errors                                               

These relative modules were not found:

* ../../../static/btn-border.svg in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
* ../../../static/hero@2x.png in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
* ../../../static/icon-search.svg in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
```

**Comment by boygirl** [comment]
@ryan-roemer this was working correctly last week _after_ I moved all my `dependencies` to `devDependencies`, and all the assets it's complaining about are local to this repo. I did have _another_ css plugin problem last week that required a change: https://github.com/FormidableLabs/victory-docs/pull/568

**Comment by ryan-roemer** [comment]
I'm seeing this in current `victory-docs@master`:

```
$ yarn start
yarn run v1.9.4
$ gatsby develop
success delete html and css files from previous builds — 0.084 s
success open and validate gatsby-config — 0.010 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.033 s
success onPreBootstrap — 0.454 s
success source and transform nodes — 0.472 s
success building schema — 0.470 s
success createLayouts — 0.009 s
success createPages — 3.714 s
success createPagesStatefully — 0.391 s
success onPreExtractQueries — 0.001 s
success update schema — 0.196 s
success extract queries from components — 0.169 s
success run graphql queries — 1.071 s
success write out page data — 0.006 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 10.381 s


src/styles/styles.css
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]

 ERROR  Failed to compile with 3 errors                                                                                                                12:14:42

These relative modules were not found:

* ../../../static/btn-border.svg in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
* ../../../static/hero@2x.png in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
* ../../../static/icon-search.svg in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
 WAIT  Compiling...                                                                                                                                    12:14:42

 ERROR  Failed to compile with 3 errors                                                                                                                12:14:43

These relative modules were not found:

* ../../../static/btn-border.svg in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
* ../../../static/hero@2x.png in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css
* ../../../static/icon-search.svg in ./~/css-loader!./~/postcss-loader!./src/styles/styles.css

```

**Comment by ryan-roemer** [comment]
Captured `yarn start` failure in https://github.com/FormidableLabs/victory-docs/issues/573

**Comment by ryan-roemer** [comment]
Note: **not** releasing per figuring out #573

**Pull request merged**
