### PR TITLE
Improve page speed performance

### PR DESCRIPTION
**Pull request by NgoKnows**
This PR makes some page speed performance improvements.

## All Pages

- Update `styled-components` to v5
- Remove unused google fonts
- Update `victory`

## Home Page

- Lazy render guide charts
- Use `date-fns` in place of `moment`
- Remove extra calculation in hero chart
- **Lighthouse Score Change**

    **Mobile:** 24 → 45

    **Desktop:** 87 → 94

## Gallery Page*
*Switching to this page is noticeably faster
- Lazy render gallery examples
- **Lighthouse Score Change**

    **Mobile:** 12 → 41

    **Desktop:** 66 → 81

## About Page

- Lazy load images
- Decrease size (dimensions) of images
- **Lighthouse Score Change**

    **Mobile:**  58 → 66

    **Desktop:** 82 → 92

### CODE REVIEW

**Comment by boygirl** [comment]
@NgoKnows Travis was complaining about an out of date lockfile. Mind installing / commiting `yarn.lock` again?

**Comment by boygirl** [comment]
@NgoKnows I think the node version in the travis config needs to be updated to at least 10 work with some deps you intorduced with these changes.

**Comment by boygirl** [comment]
@NgoKnows it looks like there's a style regression for playgrounds. I think it may be related to the `styled-components` upgrade, since switching back to master maintains the version I see on this branch until I do a fresh `yarn install`

on master with a fresh yarn install:
Screen Shot 2020-06-08 at 4 00 25 PM

on this branch with a fresh yarn install:
Screen Shot 2020-06-08 at 4 00 33 PM

**Comment by boygirl** [comment]
@NgoKnows Awesome improvements! Thank you so much! I left a few comments, but this otherwise is looking great

**Comment by NgoKnows** [comment]
Good catch! I've fixed that issue up, and this should be good to go! @boygirl

**Comment by boygirl** [comment]
@NgoKnows Thanks! I'll get this merged and deployed.

**Pull request merged**
