### PR TITLE
Fix static site generation

### PR DESCRIPTION
**Pull request by paulathevalley**
Revert victory so that the build works! 

TODO: 
- [ ] Visually inspect all the routes

### CODE REVIEW

**Comment by boygirl** [comment]
@paulathevalley this can't be the solution. We're using beta versioning for the main victory package, so `0.12.x` -> `0.13.x` is a major version bump

**Comment by paulathevalley** [comment]
@boygirl Ok! We are trying to get `victory-docs` back to a working state, and this is the short-term solution. Looking forward to hearing more about the potential breaking issue in `victory-core`.

**Comment by boygirl** [comment]
cc/ @paulathevalley https://github.com/FormidableLabs/victory-docs/pull/204 just reverts the bad changes

**Comment by paulathevalley** [comment]
Thanks @boygirl ! Closing this one.

**Pull request closed without merging**
