### PR TITLE
update theme api

### PR DESCRIPTION
**Pull request by boygirl**
cc/ @chrisbolin this update goes along with my changes to the theme API about to be released in victory. The changes are already on master there if you want to link. I deleted the comments in the theme-park playground, as comments were also breaking the playground on the front page. I'm not sure why.

### CODE REVIEW

**Comment by boygirl** [comment]
@chrisbolin I'm not sure why this is failing. I'm all the routes work locally. Did I miss something?

**Comment by chrisbolin** [comment]
hmm, @boygirl do you know what this is?
`Not compatible with your operating system or architecture: fsevents@1.0.14`

Both travis builds failed, but in different ways.
- Node 5, error above
- Node 4, `Cannot resolve module 'victory-chart/docs/victory-theme/docs' `

I'm going to restart them

**Comment by chrisbolin** [comment]
I get this locally too `Module not found: Error: Cannot resolve module 'victory-chart/docs/victory-theme/docs' in /Users/chris/formidable/victory-docs/src/components`

**Comment by chrisbolin** [comment]
maybe you have something `linked`?

**Comment by chrisbolin** [comment]
Ah, so `package.json` doesn't have a dependency on `victory-chart`, but in `config.js` there is

`import VThemeDocs from "victory-chart/docs/victory-theme/docs";`

**Comment by paulathevalley** [comment]
@chrisbolin Hmm, that line hasn’t been a problem before. Since `victory` pulls in `victory-chart` and it all gets flattened, it’s found it ok. 

To make matters worse, I nuked `node_modules` and got no errors when running `builder run build-static` locally.

**Comment by paulathevalley** [comment]
Is this the wrong version of `victory-chart`? https://travis-ci.com/FormidableLabs/victory-docs/jobs/48251132#L1306

**Comment by chrisbolin** [comment]
ahh, the master branch depends on victory-chart directly:
https://github.com/FormidableLabs/victory-docs/blob/master/package.json#L51

(that's from live-chart, which didn't work with victory core at the time :P )

**Comment by chrisbolin** [comment]
I'll push a fix to this branch and we'll _see what happens_.

**Comment by boygirl** [comment]
Woo! Please feel free to merge this if it passes CI and you're all okay with the changes

**Comment by paulathevalley** [comment]
@boygirl :( Now that the repo is public, we are migrating over to travis-ci.org and need to reconfigure travis. Apologies! We’ll get the reconfiguration resolved first.

**Comment by chrisbolin** [comment]
this LGTM. I'll merge!

**Pull request merged**
