### PR TITLE
Add custom catch-links plugin to do SPA navigation on same domain links

### PR DESCRIPTION
**Pull request by stefvhuynh**

### CODE REVIEW

**Comment by stefvhuynh** [comment]
@boygirl, i think this should do it, but it's hard to test.

**Comment by ryan-roemer** [comment]
@stefvhuynh -- Let's make sure this is linted and part of our CI 😉

**Comment by stefvhuynh** [comment]
@ryan-roemer, lint issues fixed. do you mean to get CI to fail if there are just warnings in lint?

**Comment by ryan-roemer** [comment]
@stefvhuynh -- Looking at https://github.com/FormidableLabs/victory-docs/blob/master/package.json#L89

```js
    "lint:js": "eslint --ext .js src",
```

`plugins` notably **isn't** in that list. 

In the code, `plugins` has ASI all over the place and other things that should be failing CI.

**Comment by boygirl** [comment]
What the hell, Travis?

**Comment by ryan-roemer** [comment]
@boygirl -- I think you can always manually restart those builds if needed. An the "nuclear" option I sometimes use is closing and immediately re-opening a PR...

... @stefvhuynh still has more commits to add, so maybe we just wait until he's fully done and see then if Travis is finally running ...

**Comment by boygirl** [comment]
@stefvhuynh Can you take another look at this. CI is failing on a test error.

**Comment by stefvhuynh** [comment]
@boygirl, I changed the `fileMock.js` and `styleMock.js` files to `file-mock.js` and `style-mock.js`, respectively. I changed these in the package.json on line 99 and 100. It looks like this change might be causing the failures, but I don't see these files being referenced anywhere else. Do you have any ideas?

**Comment by boygirl** [comment]
@stefvhuynh nope, I think package.json is the only place those were referenced. Maybe the naming is something jest specific? That doesn't seem like it should be the case, though

**Comment by boygirl** [comment]
:tada:

**Pull request merged**
