### PR TITLE
Add victory zoom docs

### PR DESCRIPTION
**Pull request by imranolas**
Waiting on https://github.com/FormidableLabs/victory-chart/pull/410

/cc @jevakallio

### CODE REVIEW

**Comment by paulathevalley** [comment]
LGTM! 

@boygirl would you like to proofread any content additions?

**Comment by boygirl** [comment]
Approved pending pan / zoom release

**Comment by imranolas** [comment]
I'm getting myself into a mess building these guides due to having to npm link a bunch of dependencies. I'll hold off until pan/zoom has landed as it'll make this process a great deal easier and quicker.

**Comment by boygirl** [comment]
@paulathevalley @imranolas `victory@0.13.5` is published and includes `VictoryZoom`, so this PR should be good to go

**Comment by boygirl** [comment]
Scratch that, We reverted VictoryZoom and the global animation timer in `victory@0.13.6` because it was breaking the static build

**Comment by paulathevalley** [comment]
Ok. To confirm, this means it’s not being included in the DF push, right?

**Comment by boygirl** [comment]
If we can fix it in time that would be aces, but as is, no

**Comment by imranolas** [comment]
Guides added :)

**Comment by boygirl** [comment]
:tada: looking good

**Pull request merged**
