### PR TITLE
Task add logos

### PR DESCRIPTION
**Pull request by paulathevalley**
- Add company logos to homepage
- Reorganize components into 3 columns on the homepage and on the sidebar

Resolves https://github.com/FormidableLabs/victory-docs/issues/9 

/cc @boygirl @eastridge 

screenshots: 
screen shot 2016-04-29 at 2 06 43 pm

screen shot 2016-04-29 at 4 12 58 pm

screen shot 2016-04-29 at 4 19 21 pm

### CODE REVIEW

**Comment by boygirl** [comment]
@paulathevalley this looks good to me, but I think `VictoryConstraints` and `VictoryTooltip` belong under core. I think the heading "PIE" should be something different since other types of data-viz will be nested under that heading as we build them. Approved otherwise.

**Comment by paulathevalley** [comment]
@boygirl Ok! Will do. 

I am really struggling with the heading terminology. My only other idea is Chart Figure and Other Figures, but I don’t think it’s particularly clear. 
Axis-Based, and Freestanding? 
Chart, Grid, Radial, Tree? 
2D, 3D, Radial, and Sphere?

**Comment by boygirl** [comment]
maybe just Core, Chart, and More

**Comment by paulathevalley** [comment]
Done! 
I heard mixed reports on NCR’s usage, and my message to confirm their usage went unanswered. Playing it conservative and removing it for now.

**Pull request merged**
