### PR TITLE
[WIP] Add content

### PR DESCRIPTION
**Pull request by boygirl**
cc/ @paulathevalley 

More to go, but here's a start. A few things I've noticed from running these locally

- links are not visible enough once clicked
- intra-page anchor links are not working properly (I tried adding an id to link to). I like how linking works in these docs https://github.com/d3/d3-shape#arc_outerRadius
- I think all the fonts should be smaller. It's looking especially odd in the code blocks
- I would prefer highlighting around text set of by single back ticks to match code block background
- Syntax highlighting in the code blocks

### CODE REVIEW

**Comment by paulathevalley** [comment]
@boygirl I moved your design requests to this issue: https://github.com/FormidableLabs/victory-docs/issues/148 and assigned @ebrillhart for proofreading, spellcheck, tone, voice, and all the other wonderful things.

**Comment by boygirl** [comment]
@paulathevalley sounds good to me. Many more pages of docs to come, but we can merge this sooner if you want content to style, or smaller chunks of technical writing to have to edit in a single go.

**Comment by ebrillhart** [comment]
@boygirl feel free to go ahead and add all the docs updates to this branch, and then I'll review/edit/merge on Wednesday if that sounds good to you!

**Comment by boygirl** [comment]
@ebrillhart that works for me. @paulathevalley is that alright with you in terms of working with the other todo items around styling and anchors?

**Comment by paulathevalley** [comment]
@boygirl :+1: Yes! I'll look into those in another branch.

**Comment by ebrillhart** [comment]
@boygirl lmk when you're done adding content and I'll start reviewing! are you okay with me pulling this down and making changes directly in this branch or should I make a sub-branch?

**Comment by boygirl** [comment]
Outstanding TODOS

- [ ] victory-animation
- [ ] victory-transition
- [ ] victory-shared-events
- [ ] victory-clip-container
- [ ] victory-theme

I'm considering lumping victory-animation and victory-transition into something like guide/animations. Ditto shared-events => guide/events. Thoughts?

**Comment by ebrillhart** [comment]
@boygirl I think those ideas make sense!

**Comment by paulathevalley** [comment]
@boygirl Since you are the most familiar with Victory, I think you have the best context for how to organize the content!

Just let us know if you remove any routes that are currently in production, because we will need to make sure they have redirects. (I'm not actually sure how to handle that right now—is a client-side redirect enough?)

**Comment by boygirl** [comment]
@paulathevalley I think the only thing that would be removed would be `/docs/victory-animation`, but maybe it makes sense to have brief API docs for everything and just link to the in depth guides.

**Comment by paulathevalley** [comment]
@boygirl Either way works! 

If you want a 1:1 relationship between what’s available from `victory-core` and the list of items under the "Core" heading in the sidebar, then it would make sense to keep it... does it add clarity when browsing the `victory-core` repo, for example? 
 
If the answers are no, then a singular guide would be enough. 

By the way, are Guides going to be added for the relaunch as well? What's their relationship to Recipes? Will Guides have ecology? Asking for layout reasons!

**Comment by boygirl** [comment]
@paulathevalley I'll try to get the guides written on the plane. I think guides and recipes might be the same thing. Some of the recipes, like "tooltip" should go away. Others could be generalized and beefed up. I'll work on this.

**Comment by paulathevalley** [comment]
@boygirl Awesome! I had high hopes that Recipes would become more Guide-like. :)

**Comment by boygirl** [comment]
@paulathevalley Sorry I missed on some of the content. I think the only missing routes changes are that `/recipes/tooltip` and `/recipes/shared-events` should both go away and be replaced by `/recipes/events`, and `recipes/animations` should be added.

**Comment by paulathevalley** [comment]
@boygirl @ebrillhart Would either of you be willing to squash the commits into one or two commits for this PR?

Since I have not added redirects with the static site generator before, I don't think I'll be able to figure it out in a couple of hours in addition to finishing up the design inspection. I see two options: allow them to be broken or keep the pages and add a link that says "This page is deprecated. Visit this other recipe now" or something. What do you two think?

**Pull request merged**
