### PR TITLE
Add new 404 page with new designs and sidebar

### PR DESCRIPTION
**Pull request by wgolledge**
## Changes

- Add the sidebar to the 404 page
- Update the 404 page styling in line with Zeplin designs 

## Outstanding

- I'm guessing we might like to change the footer to be rendered under the sidebar at some point?

image

### CODE REVIEW

**Comment by wgolledge** [comment]
Agree on the sidebar. I added it to the 404 page because I thought it was supposed to be on there based on the designs? Maybe I took them too literally ha.

I think footer below the sidebar would be nice but could go in a separate PR because it applies to /docs as well

**Comment by BrittanyIRL** [comment]
> I think footer below the sidebar would be nice but could go in a separate PR because it applies to /docs as well

I agree separate PR for the footer/sidebar

**Comment by wgolledge** [comment]
@boygirl could you please confirm whether you'd like the Sidebar on 404 pages? 🙂

**Comment by boygirl** [comment]
@wgolledge I think we need to keep it since we don't have a top nav on mobile sizes

**Pull request merged**
