### PR TITLE
Make Travis Work on Public Repo

### PR DESCRIPTION
**Pull request by chrisbolin**
i tried to follow the instructions on https://github.com/FormidableLabs/victory-docs/issues/51

### CODE REVIEW

**Comment by paulathevalley** [comment]
@chrisbolin Ack, there’s a missing step. So, the private github repos can only be hosted on travis-ci.com, which is where `victory-docs` is right now. It needs to be transitioned to travis-ci.org, which is the free version of travis for all public github repos. 

I turned on travis for `victory-docs` here: https://travis-ci.org/FormidableLabs/victory-docs/settings and that’s where these encrypted files need to live.

I’m going to wait for @ebrillhart’s copy change PR to get merged, and then turn off the private travis for `victory-docs`.

**Comment by chrisbolin** [comment]
@paulathevalley awesome! just let me know when we're good to go and I can finish it from here

**Comment by paulathevalley** [comment]
@chrisbolin All finished! I will turn off private travis.

**Comment by paulathevalley** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
