### PR TITLE
Feature: Add individual gallery pages #289

### PR DESCRIPTION
**Pull request by paulathevalley**
#289  

Add individual gallery pages

screen shot 2017-05-08 at 4 59 56 pm

### CODE REVIEW

**Comment by boygirl** [comment]
@paulathevalley This looks good to me pending two small changes

- Please add a gallery link to the header.
- Can you give the gallery page more obvious hover styles? The grey -> black on the visited links is especially subtle.

**Comment by paulathevalley** [comment]
> Can you give the gallery page more obvious hover styles? The grey -> black on the visited links is especially subtle.

This is true for the entire site, so should it change everywhere for consistency?

**Comment by boygirl** [comment]
Hmm. I think the sidebar links go black / grey -> red when hovered. Can it just match that?

**Comment by paulathevalley** [comment]
Yep!

**Comment by paulathevalley** [comment]
Ready for re-review.

* Change the links to red on hover
* Fix grid of gallery and homepage on Safari

**Comment by boygirl** [comment]
@paulathevalley sorry I missed this before. Can you style the individual gallery pages so that stuff like this example doesn't need to be tweaked to work:
screen shot 2017-05-09 at 3 55 00 pm

**Comment by paulathevalley** [comment]
Done! Good eye :)

screen shot 2017-05-09 at 4 17 47 pm

**Comment by boygirl** [comment]
Approved!

**Pull request merged**
